micronaut:
  application:
    name: marAnalysisBackend
  server:
    netty:
        log-level: TRACE    
    cors:
        enabled: true
        configurations:
#           web:
#             exposedHeaders:
#               - Content-Type
#               - Authorization
#               - '*'
             allowedOrigins:
               - http://localhost:3000
#        single-header: true
#    ssl:
#        enabled: true
#        buildSelfSigned: true 

#  router:
#    static-resources:
#      default:
#        enabled: true
#        mapping: "/static/**"
#        paths: classpath:frontend
netty:
  default:
    allocator:
      max-order: 3
