export const SEARCHBAR_DEBOUNCE_MS = 300;

export const DEFAULT_NUMBER_OF_ITERATIONS = 20;
export const INITIAL_LABEL_SIZE = 14;
export const INITIAL_LABEL_THRESHOLD = 0;
export const INITIAL_SHOW_UNCONNECTED_NODES = true;
export const INITIAL_NODE_SIZE = 2;
