package mar.artefacts;

public class BuiltinMetamodels {
	public static final BuiltinMetamodels INSTANCE = new BuiltinMetamodels();
	
	private static String[] METAMODELS = new String[] {
			"http:///org/eclipse/emf/ecore/util/DateConversionDelegateAnnotation",
			"http:///org/eclipse/emf/ecore/util/EcoreAnnotation", "http:///org/eclipse/emf/ecore/util/ExtendedMetaData",
			"http://eclipse.org/emf/emfstore/common/model", "http://maven.apache.org/POM/4.0.0",
			"http://org/eclipse/emf/ecp/view/categorization/model",
			"http://org/eclipse/emf/ecp/view/compoundcontrol/model", "http://org/eclipse/emf/ecp/view/custom/model",
			"http://org/eclipse/emf/ecp/view/group/model", "http://org/eclipse/emf/ecp/view/horizontal/model",
			"http://org/eclipse/emf/ecp/view/label/model", "http://org/eclipse/emf/ecp/view/model/1180",
			"http://org/eclipse/emf/ecp/view/rule/model", "http://org/eclipse/emf/ecp/view/stack/model",
			"http://org/eclipse/emf/ecp/view/table/model/150", "http://org/eclipse/emf/ecp/view/template/model",
			"http://org/eclipse/emf/ecp/view/treemasterview/model", "http://org/eclipse/emf/ecp/view/vertical/model",
			"http://org/eclipse/emf/ecp/view/viewproxy/model", "http://org/eclipse/emf/emfforms/view/annotation/model",
			"http://org/eclipse/emfforms/view/indexsegment/model/1190",
			"http://org/eclipse/emfforms/view/mappingsegment/model/1190",
			"http://org/eclipse/emfforms/view/multisegment/model/1190", "http://www.archimatetool.com/archimate",
			"http://www.bolton.ac.uk/archimate", "http://www.eclipse.org/2008/Xtext",
			"http://www.eclipse.org/CDO/releng/predicates/1.0", "http://www.eclipse.org/CDO/releng/preferences/1.0",
			"http://www.eclipse.org/CDO/releng/projectconfig/1.0", "http://www.eclipse.org/CDO/releng/setup/1.0",
			"http://www.eclipse.org/CDO/releng/workingsets/1.0", "http://www.eclipse.org/eef",
			"http://www.eclipse.org/eef/ext/widgets/reference", "http://www.eclipse.org/emf/2002/Ecore",
			"http://www.eclipse.org/emf/2002/GenModel", "http://www.eclipse.org/emf/2002/Mapping",
			"http://www.eclipse.org/emf/2002/Tree", "http://www.eclipse.org/emf/2002/XSD2Ecore",
			"http://www.eclipse.org/emf/2003/Change", "http://www.eclipse.org/emf/2003/XMLType",
			"http://www.eclipse.org/emf/2004/Ecore2Ecore", "http://www.eclipse.org/emf/2005/Ecore2XML",
			"http://www.eclipse.org/emf/2009/Validation",
			"http://www.eclipse.org/emf/CDO/admin/RepositoryCatalog/4.3.0",
			"http://www.eclipse.org/emf/CDO/Eresource/4.0.0", "http://www.eclipse.org/emf/CDO/Etypes/4.0.0",
			"http://www.eclipse.org/emf/CDO/expressions/4.3.0", "http://www.eclipse.org/emf/CDO/security/4.1.0",
			"http://www.eclipse.org/emf/compare", "http://www.eclipse.org/emf/compare/diagram/2.0",
			"http://www.eclipse.org/emf/ecp/view/indexdmr/model",
			"http://www.eclipse.org/emf/ecp/view/mappingdmr/model",
			"http://www.eclipse.org/emf/ecp/view/reference/table/selection",
			"http://www.eclipse.org/emf/ecp/view/template/selector/annotation/model",
			"http://www.eclipse.org/emf/ecp/view/template/selector/bool/model",
			"http://www.eclipse.org/emf/ecp/view/template/selector/domainmodelreference/model",
			"http://www.eclipse.org/emf/ecp/view/template/selector/hierarchy/model",
			"http://www.eclipse.org/emf/ecp/view/template/selector/viewmodelelement/model",
			"http://www.eclipse.org/emf/ecp/view/template/style/alignment/model",
			"http://www.eclipse.org/emf/ecp/view/template/style/background/model",
			"http://www.eclipse.org/emf/ecp/view/template/style/fontProperties/model",
			"http://www.eclipse.org/emf/ecp/view/template/style/keybinding/model",
			"http://www.eclipse.org/emf/ecp/view/template/style/labelwidth/model",
			"http://www.eclipse.org/emf/ecp/view/template/style/mandatory/model",
			"http://www.eclipse.org/emf/ecp/view/template/style/reference/model",
			"http://www.eclipse.org/emf/ecp/view/template/style/tab/model",
			"http://www.eclipse.org/emf/ecp/view/template/style/table/model",
			"http://www.eclipse.org/emf/ecp/view/template/style/table/validation/model",
			"http://www.eclipse.org/emf/ecp/view/template/style/textcontrol/enablement/model",
			"http://www.eclipse.org/emf/ecp/view/template/style/unsettable/model",
			"http://www.eclipse.org/emf/ecp/view/template/style/validation/model",
			"http://www.eclipse.org/emf/ecp/view/template/style/wrap/model",
			"http://www.eclipse.org/emf/edapt/declaration/0.3", "http://www.eclipse.org/emf/edapt/history/0.3",
			"http://www.eclipse.org/emf/edapt/migration/0.3", "http://www.eclipse.org/emf/parsley/dsl/EmfParsleyDsl",
			"http://www.eclipse.org/gmf/examples/runtime/1.0.0/logicsemantic",
			"http://www.eclipse.org/gmf/runtime/1.0.0/notation", "http://www.eclipse.org/gmf/runtime/1.0.1/notation",
			"http://www.eclipse.org/gmf/runtime/1.0.2/notation", "http://www.eclipse.org/ocl/1.1.0/Ecore",
			"http://www.eclipse.org/ocl/1.1.0/OCL/CST", "http://www.eclipse.org/ocl/1.1.0/OCL/Expressions",
			"http://www.eclipse.org/ocl/1.1.0/OCL/Types", "http://www.eclipse.org/ocl/1.1.0/OCL/Utilities",
			"http://www.eclipse.org/ocl/1.1.0/UML", "http://www.eclipse.org/oomph/base/1.0",
			"http://www.eclipse.org/oomph/p2/1.0", "http://www.eclipse.org/oomph/predicates/1.0",
			"http://www.eclipse.org/Oomph/preferences/1.0", "http://www.eclipse.org/oomph/resources/1.0",
			"http://www.eclipse.org/oomph/setup/1.0", "http://www.eclipse.org/oomph/setup/p2/1.0",
			"http://www.eclipse.org/oomph/setup/sync/1.0", "http://www.eclipse.org/oomph/workingsets/1.0",
			"http://www.eclipse.org/sirius/1.1.0", "http://www.eclipse.org/sirius/description/1.1.0",
			"http://www.eclipse.org/sirius/description/audit/1.1.0",
			"http://www.eclipse.org/sirius/description/style/1.1.0",
			"http://www.eclipse.org/sirius/description/tool/1.1.0",
			"http://www.eclipse.org/sirius/description/validation/1.1.0", "http://www.eclipse.org/sirius/diagram/1.1.0",
			"http://www.eclipse.org/sirius/diagram/description/1.1.0",
			"http://www.eclipse.org/sirius/diagram/description/concern/1.1.0",
			"http://www.eclipse.org/sirius/diagram/description/filter/1.1.0",
			"http://www.eclipse.org/sirius/diagram/description/style/1.1.0",
			"http://www.eclipse.org/sirius/diagram/description/tool/1.1.0",
			"http://www.eclipse.org/sirius/diagram/sequence/2.0.0",
			"http://www.eclipse.org/sirius/diagram/sequence/description/2.0.0",
			"http://www.eclipse.org/sirius/diagram/sequence/description/tool/2.0.0",
			"http://www.eclipse.org/sirius/diagram/sequence/ordering/2.0.0",
			"http://www.eclipse.org/sirius/diagram/sequence/template/2.0.0",
			"http://www.eclipse.org/sirius/dsl/formatdata/1.1.0", "http://www.eclipse.org/sirius/properties/1.0.0",
			"http://www.eclipse.org/sirius/properties/1.0.0/ext/widgets/reference",
			"http://www.eclipse.org/sirius/table/1.1.0", "http://www.eclipse.org/sirius/table/description/1.1.0",
			"http://www.eclipse.org/sirius/tree/1.0.0", "http://www.eclipse.org/sirius/tree/description/1.0.0",
			"http://www.eclipse.org/ui/2010/UIModel/application",
			"http://www.eclipse.org/ui/2010/UIModel/application/commands",
			"http://www.eclipse.org/ui/2010/UIModel/application/descriptor/basic",
			"http://www.eclipse.org/ui/2010/UIModel/application/ui",
			"http://www.eclipse.org/ui/2010/UIModel/application/ui/advanced",
			"http://www.eclipse.org/ui/2010/UIModel/application/ui/basic",
			"http://www.eclipse.org/ui/2010/UIModel/application/ui/menu",
			"http://www.eclipse.org/ui/2010/UIModel/fragment", "http://www.eclipse.org/uml2/1.1.0/GenModel",
			"http://www.eclipse.org/uml2/2.0.0/UML", "http://www.eclipse.org/uml2/2.1.0/UML",
			"http://www.eclipse.org/uml2/2.2.0/GenModel", "http://www.eclipse.org/uml2/3.0.0/UML",
			"http://www.eclipse.org/uml2/4.0.0/Types", "http://www.eclipse.org/uml2/4.0.0/UML",
			"http://www.eclipse.org/uml2/4.0.0/UML/Profile/L2", "http://www.eclipse.org/uml2/4.0.0/UML/Profile/L3",
			"http://www.eclipse.org/uml2/5.0.0/Types", "http://www.eclipse.org/uml2/5.0.0/UML",
			"http://www.eclipse.org/uml2/5.0.0/UML/Profile/Standard", "http://www.eclipse.org/uml2/schemas/Standard/1",
			"http://www.eclipse.org/xsd/2002/XSD", "http://www.eclipse.org/xtext/builderstate/1.0",
			"http://www.eclipse.org/xtext/codetemplate/Codetemplates",
			"http://www.eclipse.org/xtext/common/JavaVMTypes", "http://www.eclipse.org/xtext/trace/debug/1.0",
			"http://www.eclipse.org/Xtext/Xbase/XAnnotations", "http://www.eclipse.org/xtext/xbase/Xbase",
			"http://www.eclipse.org/xtext/xbase/Xtype", "http://www.w3.org/XML/1998/namespace",
			"https://www.eclipse.org/epp/logging/aeri/core/2.0", 
			// Others which are not in Eclipse modelling but can be added via plug-ins
			"http://www.eclipse.org/xtend"
	
	};

	public boolean isBuiltin(String uri) {
		for (String string : METAMODELS) {
			if (string.equals(uri)) {
				return true;
			}
		}
		return false;
	}
}
